"use strict";
const fs=require('fs'),crypto=require('crypto'),{percentile}=require('./bm_latency_benchmark'),meter=require('./bm_decisions_meter');
const {presentation,numericValues}=require('./bm_retrieval_wide_report');
const arg=(k,d)=>process.argv.includes(k)?process.argv[process.argv.indexOf(k)+1]:d;
const sha=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function stats(rows,rates){const successful=rows.filter(r=>r.passed),requests=rows.flatMap(r=>r.provider_requests),costs=requests.map(r=>meter.estimate(r,rates));return {attempted:rows.length,successful:successful.length,errors:rows.length-successful.length,first_text_ms:{p50:percentile(successful.map(r=>r.first_text_ms),.5),p95:percentile(successful.map(r=>r.first_text_ms),.95)},final_ms:{p50:percentile(successful.map(r=>r.elapsed_ms),.5),p95:percentile(successful.map(r=>r.elapsed_ms),.95)},provider_requests:requests.length,unknown_usage_requests:costs.filter(c=>c===null).length,known_estimated_cost_usd:costs.reduce((n,c)=>n+(c||0),0),full_estimated_cost_usd:costs.every(c=>c!==null)?costs.reduce((n,c)=>n+c,0):null};}
function main(){const input=arg('--input','tmp/decisions-production/holdout.json'),qualityFile=arg('--quality','tmp/decisions-production/quality.json'),r=JSON.parse(fs.readFileSync(input)),quality=fs.existsSync(qualityFile)?JSON.parse(fs.readFileSync(qualityFile)):null;
 const factual=x=>['sleep_yesterday','sleep_week','protection_yesterday','protection_week'].includes(x.group)||(x.group==='contextual'&&x.step===0);
 const accelerated=x=>x.retrieval_trace.some(t=>t.event==='bm_retrieval_step_answer'&&t.accepted),summary=Object.fromEntries(['optimized','decisions'].map(v=>{const rows=r.records.filter(x=>x.variant===v);return [v,{all:stats(rows,r.rates),factual:stats(rows.filter(factual),r.rates),outside_scope:stats(rows.filter(x=>!factual(x)),r.rates),accelerated:stats(rows.filter(accelerated),r.rates)}];}));
 const reviews=quality?.source_run_id===r.run_id?quality.reviews:[];
 const turns=require('./bm_retrieval_wide_quality').buildTurns(r),reviewDigest=require('./bm_sol_quality_judge').reviewDigest;
 const reviewComplete=quality?.complete===true&&reviews.length===r.records.length&&turns.every(t=>reviews.some(v=>v.conversation_id===t.conversation_id&&v.turn===t.turn&&v.input_sha256===reviewDigest(t,t.history||[])));
 const checks=r.records.map((x,i)=>{const text=x.synthetic_response||'',review=reviews.find(v=>v.conversation_id===x.variant+':'+x.pair&&v.turn===x.step&&v.input_sha256===reviewDigest(turns[i],turns[i].history||[])),issues=presentation(text,x.synthetic_input);if(/--|[\u2013\u2014]/u.test(text))issues.push('dash_punctuation');
  const values=numericValues(text),expected=x.expected.minutes,knownFact=x.eligible&&expected!==null&&!x.expected.invalid_units;
  const numericMismatch=knownFact&&!values.some(v=>Math.abs(v-expected)<=1);
  return {case_id:x.case_id,pair:x.pair,step:x.step,variant:x.variant,accelerated:accelerated(x),functional:x.passed,response_sha256:sha(text),history_sha256:sha(x.expected.history),source_and_response_record:input+'#/records/'+r.records.indexOf(x),presentation_issues:issues,numeric_mismatch_requires_review:numericMismatch,model_verdict:review?.review?.verdict||null,model_hard_contradiction:review?.review?.hard_contradiction||false,model_unsafe_claim:review?.review?.unsafe_claim||false};});
 const improvement=(a,b)=>a>0&&b!=null?100*(a-b)/a:null,a=summary.optimized.factual,b=summary.decisions.factual;
 const metrics={first_text_p50_percent:improvement(a.first_text_ms.p50,b.first_text_ms.p50),first_text_p95_percent:improvement(a.first_text_ms.p95,b.first_text_ms.p95),final_p50_percent:improvement(a.final_ms.p50,b.final_ms.p50),final_p95_percent:improvement(a.final_ms.p95,b.final_ms.p95),full_cost_percent:improvement(a.full_estimated_cost_usd,b.full_estimated_cost_usd)};
 const outside={};for(const phase of ['first_text_ms','final_ms'])for(const p of ['p50','p95'])outside[phase+'_'+p+'_slowdown_percent']=-improvement(summary.optimized.outside_scope[phase][p],summary.decisions.outside_scope[phase][p]);
 const regressions=checks.filter(x=>x.variant==='decisions'&&!x.functional&&checks.some(y=>y.variant==='optimized'&&y.pair===x.pair&&y.step===x.step&&y.functional));
 const report={created_at:new Date().toISOString(),source_run_id:r.run_id,source_commits:r.source_commits,source_hashes:r.sourceHashes,benchmark_complete:r.complete,case_manifest_sha256:sha(r.case_manifest),review_complete:reviewComplete,review_is_model_only:true,manual_review_required:true,physical_device_tested:false,deployed_candidate_tested:false,summary,metrics,outside_scope_slowdowns:outside,noneligible_latency_gate:Object.entries(outside).every(([k,v])=>Number.isFinite(v)&&v<=(k.includes('p50')?10:20)),checks,functional_regressions:regressions,performance_and_cost_gate:Object.values(metrics).every(v=>v!==null&&v>=20),quality_gate_automated:reviewComplete&&checks.every(x=>x.functional&&!x.model_hard_contradiction&&!x.model_unsafe_claim&&(!x.accelerated||x.model_verdict&&x.model_verdict!=='poor'&&!x.presentation_issues.length)),activation_approved:false,limitations:['Successful-request latency percentiles exclude errors; all errors remain explicit gates.','Known cost is estimated from returned usage and verified rates, not an invoice. Unknown usage prevents full-cost certification.','Synthetic account fixtures use real providers and PostgreSQL. No personal production rows were read.','Automatic numeric flags require review against the exact raw source and history; they are not an accuracy oracle.']};
 const output=arg('--output','tmp/decisions-production/report.json');fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify({output,complete:r.complete,metrics,summary,functional_regressions:regressions.length,activation_approved:false}));
}
if(require.main===module)main();module.exports={stats};
