"use strict";
const fs=require('fs'),crypto=require('crypto');
const sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const inputs=['calibration.json','provider-diagnostic.json','provider-diagnostic-detail.json','holdout.json','global-holdout.json','final-holdout.json','guard-holdout.json','source-holdout.json','unit-validation.json','routes-before.json','routes-after.json','routes-factorized.json','routes-domain.json','context-validation.json','followup-validation.json','followup-broad-validation.json','release-200-diagnostic.json','release-200-active.json','release-200-final-active.json','exact-broad-validation.json'];
function main(){
 const base='tmp/decisions-production/',runs=inputs.filter(n=>fs.existsSync(base+n)).map(n=>{const raw=JSON.parse(fs.readFileSync(base+n));return {local_archive:base+n,archive_sha256:crypto.createHash('sha256').update(fs.readFileSync(base+n)).digest('hex'),evidence:JSON.parse(JSON.stringify(raw,(k,v)=>k==='synthetic_request'?undefined:v)),request_bodies_retained_in_local_archive:true};});
 const final=JSON.parse(fs.readFileSync(base+'final-report.json')),quality=JSON.parse(fs.readFileSync(base+'final-quality.json')),budget=JSON.parse(fs.readFileSync('../Codigo-retrieval/tmp/retrieval-wide/budget.json'));
 const report={schema_version:1,created_at:new Date().toISOString(),final,quality,budget,frozen_source_parity:JSON.parse(fs.readFileSync(base+'frozen-source-parity.json')),final_runtime_source_parity:JSON.parse(fs.readFileSync(base+'unit-source-parity.json')),broad_runtime_report:JSON.parse(fs.readFileSync(base+'source-report.json')),broad_model_review:JSON.parse(fs.readFileSync(base+'source-quality.json')),author_review_audit:JSON.parse(fs.readFileSync('docs/BM_DECISIONS_REVIEW_AUDIT_2026-10-09.json')),reviewer_requests:{broad:JSON.parse(fs.readFileSync(base+'source-reviewer-requests.json')),final:JSON.parse(fs.readFileSync(base+'final-reviewer-requests.json'))},environment_preflight:JSON.parse(fs.readFileSync(base+'environment-readonly.json')),schema_preflight:JSON.parse(fs.readFileSync(base+'production-schema-preflight.json')),runs,activation_approved:false,scope:'Decisions only. Real providers and isolated DB fixtures; no production personal rows, Apple publication or physical execution.'};
 // Historical final/quality remain intact; the continuation never overwrites
 // an earlier verdict or substitutes a partial review for a complete one.
 const continuationFiles=['followup-quality.json','followup-broad-quality.json','followup-broad-report.json','exact-broad-report.json','release-200-final-quality.json','release-200-quality-audit.json','release-200-final-reviewed.json','release-200-final-bound-quality.json','evaluator-integrity-e21affb.json','environment-exact-readonly.json','qa-exact-config.json','qa-e21-on-auth-smoke.json','readiness-e21-pending.json','schema-plan-hashes.json'];
 report.continuation={candidate_commit:'e21affb8db35237f31836deda998616e41b0d28b',production_on:false,qa_on:true,qa_deploy_id:'6ac90f581e087bc4cbbf0730',next_dataset:'tools/datasets/bmb_decisions_release_200_v2_2026-10-09.json',next_dataset_provider_tested:false,human_review_completed:false,physical_cases_completed:0,artifacts:continuationFiles.filter(n=>fs.existsSync(base+n)).map(n=>({local_archive:base+n,archive_sha256:crypto.createHash('sha256').update(fs.readFileSync(base+n)).digest('hex'),evidence:JSON.parse(fs.readFileSync(base+n))}))};
 const output='docs/BM_DECISIONS_GLOBAL_EVIDENCE_2026-10-09.json';fs.writeFileSync(output,JSON.stringify(report,null,2));console.log(JSON.stringify({output,runs:runs.length,records:runs.reduce((n,r)=>n+(r.evidence.records?.length||r.evidence.summary?.turns||0),0),budget,sha256:sha(report)}));
}
if(require.main===module)main();
