"use strict";
const assert = require("node:assert/strict"), fs = require("node:fs"), os = require("node:os"), path = require("node:path");
const { validateAuthorization, deploymentBody } = require("./bm_decisions_authorized_release");
const a = { id: "guillem-decisions-global-on-2026-10-09-b993", authorizer: "Guillem", instruction: "Ponlo ON, implementa autónomo", site_id: "59955668-9a9b-4979-a283-63fbf3115fe5", source_commit: "b9935d976bce6821ce23044505cfaac46041e352", global: true, budget_ceiling_usd: 24, quality_certified: false, human_pairs_reviewed: 0, physical_cases_executed: 0, pending_reviews: 92, normal_release_gate_changed: false, allow_migrations: ["026", "027", "028"] };
const p = { source_commit: a.source_commit, source_tree_clean: true, remote_function_hashes_verified: true, functions: Array.from({length:10},(_,i)=>({name:"candidate"+i,sha256:"new"+i})), status: "private_deploy_verified" };
const b = { limit_usd:24, reserved_upper_usd:23.93839122, known_usd:23.40453732 };
assert.equal(validateAuthorization(a,p,b),true);
for(const patch of [{quality_certified:true},{physical_cases_executed:20},{source_commit:"0".repeat(40)},{site_id:"qa"},{budget_ceiling_usd:26},{allow_migrations:["026","027","028","031"]},{normal_release_gate_changed:true}]) assert.throws(()=>validateAuthorization({...a,...patch},p,b));
assert.throws(()=>validateAuthorization(a,p,{...b,limit_usd:26}));
assert.throws(()=>validateAuthorization(a,p,{...b,reserved_upper_usd:24.01}));
assert.throws(()=>validateAuthorization(a,{...p,source_tree_clean:false},b));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"blank-preservation-test-"));
fs.mkdirSync(path.join(dir,".netlify/functions"),{recursive:true});
fs.writeFileSync(path.join(dir,".netlify/functions/manifest.json"),JSON.stringify({functions:p.functions.map(f=>({name:f.name,buildData:{runtimeAPIVersion:2}}))}));
const snapshot={functions:{branch:null,functions:[{n:"voice-old",d:"unchanged-voice",bd:{runtimeAPIVersion:1}},{n:"candidate0",d:"old0"}]},files:[{path:"/privacy.html",sha:"privacy"},{path:"/.well-known/apple-app-site-association",sha:"aasa"}],deploy:{function_schedules:[]}};
const body=deploymentBody(snapshot,{...p,package_directory:dir});
assert.equal(body.draft,true);assert.equal(body.functions["voice-old"],"unchanged-voice");assert.equal(body.functions.candidate0,"new0");
assert.deepEqual(body.files,{"privacy.html":"privacy",".well-known/apple-app-site-association":"aasa"});
assert.equal(Object.keys(body.functions).length,11);assert.deepEqual(body.function_schedules,[{name:"bmb-tick",cron:"*/5 * * * *"}]);
console.log("PASS one-time authorization rejects wrong source, site, certification, migration scope and budget; preserves existing voice/functions/static hashes");
