"use strict";
// Isolated reviewable overlay; never edits or publishes current QA/runtime.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
function main(){const root='tmp/retrieval-wide/integration',current='../Codigo-voice-release';fs.mkdirSync(root,{recursive:true});fs.cpSync('netlify/functions',path.join(root,'netlify/functions'),{recursive:true});fs.mkdirSync(path.join(root,'tools'),{recursive:true});
 const currentHead=cp.execFileSync('git',['-C',current,'rev-parse','HEAD'],{encoding:'utf8'}).trim();
 const file=path.join(root,'netlify/functions/bmb-brain.js');let source=fs.readFileSync(file,'utf8'),qa=fs.readFileSync(path.join(current,'netlify/functions/bmb-brain.js'),'utf8');
 const instruction=qa.split('\n').find(l=>l.startsWith('The current_sleep source contains'));if(!instruction)throw Error('current_sleep_instruction_missing');
 source=source.replace('const longitudinal=require("./bmb-longitudinal");','const longitudinal=require("./bmb-longitudinal");\nconst {sleepContext}=require("./bmb-sleep-context");');
 source=source.replace('Use read phase to query',instruction+'\nUse read phase to query');
 source=source.replace('const sources=[latest,...(proactive?.daily_review?.sources||[])];','const currentSleep=sleepContext(context);\n  const sources=[latest,currentSleep,...(proactive?.daily_review?.sources||[])];');
 source=source.replace('.prepare(retrievalRoute,{userId,identity,cutoff,','.prepare(currentSleep.available&&retrievalRoute?.startsWith("sleep_")?null:retrievalRoute,{userId,identity,cutoff,');
 source=source.replace('{source_id:"memory",source:"user declarations"}','{source_id:"current_sleep",available:currentSleep.available,source:currentSleep.source,is_synthetic:currentSleep.is_synthetic,reason:currentSleep.reason},\n      {source_id:"memory",source:"user declarations"}');
 fs.writeFileSync(file,source);fs.copyFileSync(path.join(current,'netlify/functions/bmb-sleep-context.js'),path.join(root,'netlify/functions/bmb-sleep-context.js'));fs.copyFileSync(path.join(current,'tools/bmb_sleep_context_test.js'),path.join(root,'tools/bmb_sleep_context_test.js'));
 const diff=cp.spawnSync('git',['diff','--no-index','--','netlify/functions/bmb-brain.js',file.replaceAll('\\','/')],{encoding:'utf8'});if(diff.status!==1)throw Error('integration_diff_required');fs.writeFileSync('docs/BM_RETRIEVAL_QA_INTEGRATION_2026-10-08.patch',diff.stdout.replaceAll('b/tmp/retrieval-wide/integration/netlify/functions/','b/netlify/functions/'));
 const helper=fs.readFileSync(path.join(root,'netlify/functions/bmb-sleep-context.js'),'utf8').replace(/\r\n/g,'\n').trimEnd().split('\n');fs.appendFileSync('docs/BM_RETRIEVAL_QA_INTEGRATION_2026-10-08.patch',`diff --git a/netlify/functions/bmb-sleep-context.js b/netlify/functions/bmb-sleep-context.js\nnew file mode 100644\n--- /dev/null\n+++ b/netlify/functions/bmb-sleep-context.js\n@@ -0,0 +1,${helper.length} @@\n`+helper.map(l=>'+'+l).join('\n')+'\n');
 const report={created_at:new Date().toISOString(),candidate_commit:cp.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),current_checkout_head:currentHead,deployed_sleep_fix_commit:'cb460ed7bd107e40dfc1f65aa81dc2078274a97e',files:{candidate_brain:hash('netlify/functions/bmb-brain.js'),current_brain:hash(path.join(current,'netlify/functions/bmb-brain.js')),overlay_brain:hash(file),current_sleep:hash(path.join(current,'netlify/functions/bmb-sleep-context.js'))},deployment:false,activation:false,limitation:'Prepared overlay is not timed benchmark source. Current iPhone sleep bypasses compact sleep route; no claim that accelerated route consumes current_sleep.',overlay:root};fs.writeFileSync('tmp/retrieval-wide/integration-prepared.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
if(require.main===module)main();
