"use strict";
const fs=require('fs'),path=require('path');
async function main(){const config=JSON.parse(fs.readFileSync(path.join(process.env.APPDATA,'netlify/Config/config.json'),'utf8')),token=config.users[config.userId].auth.token,id='2ef5a74e-af70-4893-a5f6-63fb2537720d';
 const get=async(route)=>{const r=await fetch('https://api.netlify.com/api/v1'+route,{headers:{authorization:'Bearer '+token},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('readonly_qa_http_'+r.status);return r.json();};
 const site=await get('/sites/'+id);if(site.id!==id||site.ssl_url!=='https://blank-product-staging-20260926.netlify.app')throw Error('private_qa_required');
 for(const suffix of ['/','/.netlify/functions/assistant-app']){const barrier=await fetch(site.ssl_url+suffix,{redirect:'manual',signal:AbortSignal.timeout(15000)});if(barrier.status!==401)throw Error('private_qa_required');await barrier.body?.cancel();}
 const vars=await get('/accounts/'+site.account_id+'/env?site_id='+id),functions=await get('/sites/'+id+'/functions'),packageFile='../Codigo-voice-release/tmp/cloud-stage/package-cb460ed7bd10-1791456138972.json',pack=JSON.parse(fs.readFileSync(packageFile));
 const flags=Object.fromEntries(['BM_RETRIEVAL_STEP_QA_ENABLED','BM_DECISIONS_QA_ENABLED','BM_JEV_PREFETCH_EXPERIMENT'].map(key=>{const v=vars.find(x=>x.key===key),values=(v?.values||[]).map(x=>x.value);return [key,{present:Boolean(v),enabled_any_context:values.some(x=>/^(true|1)$/i.test(String(x)))}];}));
 const flat=Array.isArray(functions)?functions:functions.functions||[],remote=flat.filter(fn=>(fn.n||fn.name)&&pack.functions.some(p=>p.name===(fn.n||fn.name))).map(fn=>({name:fn.n||fn.name,matches_expected:(fn.d||fn.sha)===pack.functions.find(p=>p.name===(fn.n||fn.name)).sha256}));
 const final=await get('/sites/'+id),report={created_at:new Date().toISOString(),read_only:true,site_id:id,private_barrier:true,active_deploy:site.published_deploy.id,deployed_sleep_fix:site.published_deploy.id==='6ac7738de460d6ac930c03a2',stable_deploy:final.published_deploy.id===site.published_deploy.id,flags,functions:remote,expected_functions:pack.functions.length,all_hashes_match:remote.length===pack.functions.length&&remote.every(f=>f.matches_expected),no_deploy:true,no_users_activated:true};fs.writeFileSync('tmp/retrieval-wide/qa-readonly.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
main().catch(e=>{console.error(/^(readonly_qa_http_\d+|private_qa_required)$/.test(e.message)?e.message:'readonly_qa_verification_failed:'+e.name+':'+(e.code||'unknown'));process.exitCode=1;});
