"use strict";
const fs=require('fs'),crypto=require('crypto');const sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function selectedIds(){const corpus=require('./datasets/bm_retrieval_wide_final_2026-10-08.json').cases,ids=[];const routes=['sleep_yesterday','sleep_week','protection_yesterday','protection_week'];routes.forEach((route,i)=>['es','en'].forEach((language,j)=>{const own=corpus.filter(s=>s.route===route&&s.language===language&&s.eligible);for(const index of [(i*2+j)%10,(i*2+j+4)%10])ids.push(own[index].id);}));for(const scenario of [4,14,20,39])for(const offset of [0,1])ids.push('wide-'+(81+2*scenario+offset));return ids;}
function main(){const report=JSON.parse(fs.readFileSync('tmp/retrieval-wide/final.json')),ids=selectedIds(),mapping=[],sections=[];for(const [i,id]of ids.entries()){const rows=report.records.filter(r=>r.case_id===id),last=Math.max(...rows.map(r=>r.step)),pair=rows.filter(r=>r.step===last);if(pair.length!==2)continue;const flip=parseInt(sha({run:report.run_id,id}).slice(0,2),16)%2,ordered=flip?pair.slice().reverse():pair;
 mapping.push({sample:i+1,case_id:id,A:ordered[0].variant,B:ordered[1].variant,response_sha256:ordered.map(r=>sha(r.synthetic_response))});const common=ordered[0],e=common.expected,facts={ventana_fixtures_UTC:[e.from,e.to],zona:'Europe/Madrid',sueño:e.all_fixture_sleep,proteccion:e.fixture_sessions,olvidado:e.forgotten,unidades_invalidas:e.invalid_units,ejecucion_fisica:false};if(common.eligible&&common.group.startsWith('sleep'))delete facts.proteccion;if(common.eligible&&common.group.startsWith('protection'))delete facts.sueño;let s=`## Pareja ${i+1}\n\nPregunta: ${common.synthetic_input}\n\nDatos disponibles (ficticios): ${JSON.stringify(facts)}\n\n`;
 for(const [j,row]of ordered.entries()){s+=`**Respuesta ${j===0?'A':'B'}**\n\n`;if(row.step>0)s+=`Conversación previa de esta respuesta: ${JSON.stringify(row.expected.history)}\n\n`;s+=(row.synthetic_response||'[Sin respuesta completa; error del servicio]')+'\n\n';}s+='Revisión: A __ / B __. Preferencia A / B / empate: __. Problema concreto: __.\n';sections.push(s);}
 const head='# Revisión humana ciega de retrieval\n\nPendiente: no se ha realizado ninguna evaluación humana. 24 parejas; 16 factuales y 8 de consejo, acción o contexto; ES/EN equilibrados. Tiempo estimado: 20 minutos. Primera acción: revisar la pareja 1 (60–90 segundos).\n\nLee pregunta, datos y contexto antes de ambas respuestas. Aplica el periodo de la pregunta a las fechas de los registros; la ventana de fixtures solo indica los datos disponibles. Puntúa cada respuesta: E = excelente, A = aceptable, D = deficiente. Excelente exige dato/periodo/unidades correctos, procedencia y límites honestos, contexto conservado, naturalidad y utilidad sin relleno. Aceptable tiene solo defectos leves de redacción. Deficiente cambia/inventa hechos, ignora contexto, expone etiquetas internas o afirma ejecución física sin evidencia. Elige A, B o empate; anota el defecto exacto. No hay instrucciones para ejecutar acciones reales.\n\nNo se muestran variante, tiempo, coste ni veredicto del modelo. Los registros son sintéticos. La clave de desenmascarado está separada en tmp/retrieval-wide/human-unblind.json; no consultarla hasta cerrar las puntuaciones.\n\n';
fs.writeFileSync('docs/BM_RETRIEVAL_HUMAN_REVIEW_2026-10-08.md',head+sections.join('\n'));fs.writeFileSync('tmp/retrieval-wide/human-unblind.json',JSON.stringify({run_id:report.run_id,selection:ids,mapping},null,2));console.log(JSON.stringify({pairs:sections.length,complete:sections.length===24,human_review_done:false,ids}));}
module.exports={selectedIds};if(require.main===module)main();
