"use strict";
const fs=require("node:fs"),crypto=require("node:crypto"),{summarize}=require("./bm_retrieval_step_benchmark");
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");
function load(path){const bytes=fs.readFileSync(path);return {...JSON.parse(bytes),artifact_sha256:sha(bytes)};}
function audit(b,q,strictBinding=false){
 const turns=strictBinding?require("./bm_retrieval_step_quality").buildTurns(b):null;
 if(!b.complete||!q.complete||b.records.length!==b.pair_count*2||q.reviews.length!==b.records.length||q.source_run_id!==b.run_id)throw Error("incomplete_or_unbound_evidence");
 const keys=new Set();for(const r of q.reviews){const key=r.variant+":"+r.turn;if(keys.has(key))throw Error("duplicate_review");keys.add(key);if(strictBinding){const t=turns.find(t=>t.conversation_id===key);if(!t||require("./bm_sol_quality_judge").reviewDigest(t,[],r.review.model_requested)!==r.input_sha256)throw Error("quality_digest_mismatch");}if(!b.records.some(x=>x.variant===r.variant&&x.pair===r.turn))throw Error("unbound_review");}
 const summary=summarize(b.records,b.rates),a=summary.optimized,c=summary.decisions;
 const review=v=>q.reviews.filter(r=>r.variant===v),ok=r=>["excellent","acceptable"].includes(r.review?.verdict)&&!r.review.hard_contradiction&&!r.review.unsafe_claim;
 const regressions=review("decisions").filter(r=>!ok(r)&&review("optimized").some(x=>x.turn===r.turn&&ok(x))).map(r=>({pair:r.turn,case_id:b.records.find(x=>x.variant==="decisions"&&x.pair===r.turn).case_id,review:r.review}));
 const accelerated=b.records.filter(r=>r.variant==="decisions"&&r.retrieval_trace.some(t=>t.accepted));
 const delta=(a,b)=>(b/a-1)*100;
 return {summary,quality:q.by_variant,paired_quality_regressions:regressions,accelerated:{count:accelerated.length,one_generation:accelerated.filter(r=>r.model_calls===1).length,extra_generations:accelerated.filter(r=>r.model_calls>1).map(r=>({case_id:r.case_id,calls:r.model_calls}))},changes_percent:{first_text_p50:delta(a.first_text_ms.p50,c.first_text_ms.p50),first_text_p95:delta(a.first_text_ms.p95,c.first_text_ms.p95),final_p50:delta(a.final_ms.p50,c.final_ms.p50),final_p95:delta(a.final_ms.p95,c.final_ms.p95),complete_estimated_cost:a.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd!=null?delta(a.total_estimated_cost_usd,c.total_estimated_cost_usd):null},
 gates:{visible_prose_clean:b.records.filter(r=>r.variant==="decisions").every(r=>!/[\uE200-\uE202]/u.test(r.synthetic_response||"")&&!/\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i.test(r.synthetic_response||"")),all_candidate_outputs_acceptable_by_model:review("decisions").every(ok),at_least_95_percent_excellent_by_model:review("decisions").filter(r=>r.review?.verdict==="excellent"&&ok(r)).length/review("decisions").length>=.95,no_new_paired_quality_failures:regressions.length===0,no_more_functional_errors:c.errors<=a.errors,zero_candidate_functional_errors:c.errors===0,first_text_faster:c.first_text_ms.p50<a.first_text_ms.p50,final_faster:c.final_ms.p50<a.final_ms.p50,first_text_p95_faster:c.first_text_ms.p95<a.first_text_ms.p95,final_p95_faster:c.final_ms.p95<a.final_ms.p95,lower_complete_estimated_cost:a.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd<a.total_estimated_cost_usd,cleanup_all_passed:b.cleanup.length===5&&b.cleanup.every(r=>r.passed)}};
}
function main(){const base="tmp/retrieval-iteration/",pilot=load(base+"pilot.json"),pilotQuality=load(base+"pilot-quality.json"),earlierFresh=load(base+"fresh.json"),earlierQuality=load(base+"fresh-quality.json"),earlierVerification=load(base+"fresh-source-verification.json"),fresh=load(base+"final.json"),quality=load(base+"final-quality.json"),originalGuards=load(base+"classifier-guards.json"),failedGuards=load(base+"classifier-guards-final.json"),guards=load(base+"classifier-guards-revised.json");
 const analysis=audit(fresh,quality,true),verification=[];
 for(const [variant,hashes]of Object.entries(fresh.sourceHashes))for(const [name,expected]of Object.entries(hashes)){const path=(variant==="optimized"?"../Codigo-retrieval-reference":".")+"/netlify/functions/"+name;verification.push({variant,name,expected,actual:sha(fs.readFileSync(path))});}
 if(verification.some(r=>r.expected!==r.actual)||guards.source_sha256!==sha(fs.readFileSync("netlify/functions/bm-retrieval-step.js")))throw Error("frozen_runtime_changed");
 const classifierGuards=guards.records.every(r=>r.passed)&&guards.records.filter(r=>r.split==="validation").length===16;
 const evidence={schema_version:1,generated_at:new Date().toISOString(),hypothesis:"Reduce generative selection and output work while preserving excellent responses, faster first text and durable completion, and lower complete estimated provider cost.",development:{pilot,pilot_quality:pilotQuality,analysis:audit(pilot,pilotQuality),original_guards:originalGuards,failed_threshold_guards:failedGuards,first_fresh_run:{benchmark:earlierFresh,quality:earlierQuality,analysis:audit(earlierFresh,earlierQuality),source_verification:earlierVerification}},final:{benchmark:fresh,quality,analysis},classifier_guards:guards,source_verification:verification,
 synthetic_gate_passed:classifierGuards&&Object.values(analysis.gates).every(Boolean),activation:false,
 limitations:["40 final validation questions: 20 previously executed, 20 newly authored; all authored by implementing agent, not a sealed independent human holdout","Quality is judged by another model; excellent is a model verdict, not human certification","One measured repetition per final question; timing variability and general traffic remain untested","Full cost is a per-request provider estimate, not an invoice or infrastructure bill; evaluation/setup overhead excluded","Local authenticated handler with real OpenAI and QA DB; deployed transport, iPhone and voice untested","Final comparison isolates the complete compact retrieval architecture against a shared repaired baseline, not classifier-only effect","All pilot, negative-test and fresh failures retained; no replacement of failed turns"]};
 fs.writeFileSync("docs/BM_RETRIEVAL_ITERATION_EVIDENCE_2026-10-08.json",JSON.stringify(evidence,null,2)+"\n");console.log(JSON.stringify({...analysis,classifier_guards:{passed:guards.records.filter(r=>r.passed).length,total:guards.records.length},hashes_verified:verification.length,synthetic_gate_passed:evidence.synthetic_gate_passed}));
}
if(require.main===module)try{main();}catch(e){console.error(e.message);process.exitCode=1;}
module.exports={audit};
