"use strict";
const fs=require('fs'),crypto=require('crypto'),{percentile}=require('./bm_latency_benchmark'),meter=require('./bm_decisions_meter');
const sha=x=>crypto.createHash('sha256').update(typeof x==='string'?x:JSON.stringify(x)).digest('hex');
const load=p=>JSON.parse(fs.readFileSync(p));
function presentation(text,input){const defects=[];if(/[\uE200-\uE202]/u.test(text))defects.push('citation_unicode');for(const m of text.matchAll(/\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/ig))if(!input.includes(m[0]))defects.push('uuid');for(const m of text.matchAll(/\[(?:protection_stat\w*|observations?|current_sleep|history|memory[:\w-]*)(?:[^\]]*\]|$)|\b(?:Source|Fuente)\s+(?:protec\w*|observ\w*|history|current_sleep)|\bprotection_statistics\b/ig))if(!input.includes(m[0]))defects.push('internal_reference');if(/\*\*[^*]+\*\*/.test(text))defects.push('literal_markdown');return [...new Set(defects)];}
function numericValues(text){const values=[];const combined=/(\d+(?:[.,]\d+)?)\s*(?:hours?|horas?|h)\s*(?:and|y)?\s*(\d+(?:[.,]\d+)?)\s*(?:minutes?|minutos?|min)\b/ig;let clean=text;for(const m of text.matchAll(combined)){values.push(Number(m[1].replace(',','.'))*60+Number(m[2].replace(',','.')));clean=clean.replace(m[0],'');}for(const m of clean.matchAll(/(\d+(?:[.,]\d+)?)\s*(?:(?:sleep|recorded protection|recorded protected|recorded|registered|protection|protected)\s+)?(hours?|horas?|h|minutes?|minutos?|min)\b/ig))values.push(Number(m[1].replace(',','.'))*(/^h/i.test(m[2])?60:1));return values;}
function check(r){const text=r.synthetic_response||'',issues=presentation(text,r.synthetic_input),draftIssues=(r.drafts||[]).flatMap(d=>presentation(d,r.synthetic_input));let factual='not_deterministically_judged';
 if(r.eligible&&r.passed&&!r.expected.invalid_units&&!(r.group==='sleep_yesterday'&&r.expected.available_records.length>1)){
  const values=numericValues(text),minutes=r.expected.minutes;
  if(minutes===null){factual=values.length?'unexpected_duration':'truthful_absence_requires_semantic_review';}
  else if(values.some(v=>Math.abs(v-minutes)<=1)){factual='matching_duration';}
  else if(minutes===0&&r.group.startsWith('protection')&&/no (?:hay |tienes |constan |recorded |registered |logged )?(?:minutos?|minutes?|protection)|ning[uú]n|minutos.*(?:no consta|no hay)/i.test(text)){factual='zero_phrase_requires_semantic_review';}
  else{factual='missing_or_mismatched_number';}
 }
 const route=r.retrieval_trace.find(t=>t.event==='bm_retrieval_step_timing')?.route||null;
 // Mixed conversations are grouped outside scope, but some first turns are
 // themselves closed factual questions. Do not call their valid route a breach.
 const contextualFactualStart=r.group==='context'&&r.step===0&&/^(?:Dame mi sueño registrado de ayer|Dame mi protección registrada de ayer|¿Cuánto dormí ayer|¿Cuántos minutos de protección constan ayer|Give my recorded sleep yesterday|Give my recorded protection yesterday|How long did I sleep yesterday|How many protection minutes are recorded yesterday|No guardes nuevos datos: ¿cuánto dormí ayer|Do not save new data: how long did I sleep yesterday)/i.test(r.synthetic_input);
 const guardViolation=r.variant==='decisions'&&route&&((!r.eligible&&!contextualFactualStart)||r.step>0),repeat=r.synthetic_input.match(/^(?:Repeat literally|Repite literalmente):\s*(.*)$/i),normalize=x=>x.replace(/[“”«»"]/g,'').trim().toLowerCase();
 return {case_id:r.case_id,pair:r.pair,step:r.step,variant:r.variant,response_sha256:sha(text),expected_sha256:sha(r.expected),functional:r.passed,presentation_issues:issues,draft_presentation_issues:r.transport==='local-ndjson-handler'?[...new Set(draftIssues)]:[],raw_callback_presentation_issues:r.transport==='local-json-handler'?[...new Set(draftIssues)]:[],literal_repeat_passed:repeat?normalize(text)===normalize(repeat[1]):null,zero_sleep_scope_warning:r.eligible&&r.expected.minutes===0&&r.group.startsWith('sleep')&&!/record|registr|measurement|medici[oó]n|consta|figura|dato|declar/i.test(text),factual,guard_violation:Boolean(guardViolation),selected_route:route,accelerated:r.retrieval_trace.some(t=>t.accepted===true)};
}
function metrics(rows,rates){const passed=rows.filter(r=>r.passed),req=rows.flatMap(r=>r.provider_requests),costs=req.map(r=>meter.estimate(r,rates));return {turns:rows.length,completed:passed.length,errors:rows.length-passed.length,missing_first_text:passed.filter(r=>!Number.isFinite(r.first_text_ms)).length,first_text_ms:{p50:percentile(passed.map(r=>r.first_text_ms),.5),p95:percentile(passed.map(r=>r.first_text_ms),.95)},final_ms:{p50:percentile(passed.map(r=>r.elapsed_ms),.5),p95:percentile(passed.map(r=>r.elapsed_ms),.95)},failed_final_ms:rows.filter(r=>!r.passed).map(r=>r.elapsed_ms),requests:req.length,generations:rows.reduce((n,r)=>n+r.model_calls,0),classifiers:rows.reduce((n,r)=>n+r.decisions_calls,0),known_cost_usd:costs.reduce((n,c)=>n+(c||0),0),unknown_usage:costs.filter(c=>c===null).length,total_cost_usd:costs.every(c=>c!==null)?costs.reduce((n,c)=>n+c,0):null};}
function summarize(report){const rows=report.records,rates=report.rates,summary={},matched=new Set(rows.filter(r=>r.variant==='optimized'&&r.passed&&rows.some(c=>c.variant==='decisions'&&c.pair===r.pair&&c.step===r.step&&c.passed)).map(r=>r.pair+':'+r.step));for(const v of ['optimized','decisions']){const own=rows.filter(r=>r.variant===v);summary[v]={all:metrics(own,rates),matched_completed:metrics(own.filter(r=>matched.has(r.pair+':'+r.step)),rates),eligible:metrics(own.filter(r=>r.eligible),rates),noneligible:metrics(own.filter(r=>!r.eligible),rates),accelerated:metrics(own.filter(r=>r.retrieval_trace.some(t=>t.accepted===true)),rates),subgroups:{}};for(const field of ['language','group','profile','transport','step'])for(const key of new Set(own.map(r=>r[field])))summary[v].subgroups[field+':'+key]=metrics(own.filter(r=>r[field]===key),rates);}return summary;}
function main(){const report=load('tmp/retrieval-wide/final.json'),deterministic=report.records.map(check),quality=fs.existsSync('tmp/retrieval-wide/quality.json')?load('tmp/retrieval-wide/quality.json'):null;
 if(quality){const judge=require('./bm_sol_quality_judge'),turns=require('./bm_retrieval_wide_quality').buildTurns(report);for(const review of quality.reviews){const turn=turns.find(t=>t.conversation_id===review.conversation_id&&t.turn===review.turn);if(!turn||judge.reviewDigest(turn,turn.history||[])!==review.input_sha256)throw Error('review_binding_mismatch');review.review_binding={response_sha256:sha(turn.response),expectation_sha256:sha(turn.expected),history_sha256:sha(turn.history||[]),review_input_sha256:review.input_sha256};}quality.binding_verified=true;quality.author_audit={not_independent_human:true,raw_verdicts_unchanged:true,context_oracle_limitation:'Mixed-context fixtures retain sleep-week expected.minutes=424 and fixture period even when the actual first question asks yesterday; apply the requested period to raw records. These model inputs can bias a reviewer and contextual quality totals are not a certified ground truth.',confirmed_false_positive:{case_id:'wide-160',step:0,variant:'decisions',raw_model_verdict:'poor',raw_minutes_expected:424,correct_yesterday_minutes:489,response_minutes:489,reference_also_answers_489:true,explanation:'The sole raw poor accelerated verdict and one of seven raw paired regressions is not supported by the raw dated measurements. It is retained as evaluator disagreement, not an established candidate error.'}};quality.strata={};for(const v of ['optimized','decisions']){const own=quality.reviews.filter(r=>r.variant===v),matches=(r)=>report.records.find(t=>v===t.variant&&r.conversation_id===v+':'+t.pair&&r.turn===t.step);quality.strata[v]={eligible:judge.summarize(own.filter(r=>matches(r).eligible)),noneligible:judge.summarize(own.filter(r=>!matches(r).eligible)),accelerated:judge.summarize(own.filter(r=>matches(r).retrieval_trace.some(t=>t.accepted===true)))};}quality.paired_regressions=quality.reviews.filter(r=>r.variant==='decisions'&&(r.review.verdict==='poor'||r.review.hard_contradiction||r.review.unsafe_claim)).filter(r=>{const a=quality.reviews.find(x=>x.variant==='optimized'&&x.conversation_id==='optimized:'+r.conversation_id.split(':')[1]&&x.turn===r.turn);return a&&a.review.verdict!=='poor'&&!a.review.hard_contradiction&&!a.review.unsafe_claim;}).map(r=>({conversation_id:r.conversation_id,turn:r.turn,rationale:r.review.rationale}));}
 const optional=p=>fs.existsSync(p)?load(p):null;
 const replay=optional('tmp/retrieval-wide/timing-replay.json');
 const evidence={schema_version:1,created_at:new Date().toISOString(),complete:report.complete,case_manifest_sha256:sha(fs.readFileSync('tools/datasets/bm_retrieval_wide_final_2026-10-08.json','utf8')),unique_authored_cases:report.case_manifest.cases.length,semantic_case_families:80,case_independence:'80 paired ES/EN scenario/profile families. Authored, correlated and nonrandom; no IID or population-level failure bound claimed.',multi_turn_cases:report.case_manifest.cases.filter(s=>s.turns?.length>1).length,metadata_correction:'Frozen manifest description says 24 multi-turn cases; actual fixed corpus has 22 (182 turns per variant). Questions/fixtures unchanged.',first_text_definition:'Original JSON callbacks reset before another attempt: final-attempt draft, not necessarily first-ever output. Original NDJSON and timing replay preserve first-ever nonempty draft. No earliest discarded JSON timestamp inferred.',source_run:report.run_id,summary:summarize(report),deterministic,quality,benchmark:report,timing_replay:replay?{primary_first_text_evidence:true,not_new_holdout:true,quality_verdicts_not_transferred:true,source_same_as_original:JSON.stringify(replay.sourceHashes)===JSON.stringify(report.sourceHashes),report:replay,summary:summarize(replay),deterministic:replay.records.map(check)}:null,calibration:load('tmp/retrieval-wide/calibration.json'),budget:load('tmp/retrieval-wide/budget.json'),novelty_audit:optional('tmp/retrieval-wide/novelty-audit.json'),faults:optional('tmp/retrieval-wide/faults.json'),integration_prepared:optional('tmp/retrieval-wide/integration-prepared.json'),integration_tested:optional('tmp/retrieval-wide/integration-tested.json'),qa_readonly:optional('tmp/retrieval-wide/qa-readonly.json'),source_verification:optional('tmp/retrieval-wide/source-verification.json'),reviewer_requests:optional('tmp/retrieval-wide/reviewer-requests.json'),reviewer_first_attempt_snapshot:optional('tmp/retrieval-wide/quality-first-attempt.json'),human_review_completed:false,physical_device_tested:false,deployed_candidate_tested:false};fs.writeFileSync('docs/BM_RETRIEVAL_WIDE_EVIDENCE_2026-10-08.json',JSON.stringify(evidence,null,2)+'\n');
 console.log(JSON.stringify({complete:evidence.complete,summary:Object.fromEntries(Object.entries(evidence.summary).map(([v,s])=>[v,{all:s.all,eligible:s.eligible,noneligible:s.noneligible}])),presentation_failures:deterministic.filter(r=>r.presentation_issues.length||r.draft_presentation_issues.length).length,guard_violations:deterministic.filter(r=>r.guard_violation),numeric_flags:deterministic.filter(r=>r.factual==='missing_or_mismatched_number'||r.factual==='unexpected_duration').map(r=>({case:r.case_id,variant:r.variant,factual:r.factual}))}));}
module.exports={presentation,numericValues,check,metrics,summarize};if(require.main===module)main();
