"use strict";
const assert=require('assert/strict'),fs=require('fs'),r=require('../netlify/functions/bm-retrieval-step');
const user='11111111-1111-4111-8111-111111111111',run='22222222-2222-4222-8222-222222222222',env={SUPABASE_URL:'https://njqbovsmoowkhhsqmitn.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'fixture',OPENAI_API_KEY:'fixture',BM_RETRIEVAL_STEP_QA_ENABLED:'true',BM_DECISIONS_DATA_POLICY:'synthetic-private-qa',BM_DECISIONS_QA_USERS:user};
async function main(){const records=[],info=console.info;console.info=()=>{};const test=async(name,fn)=>{await fn();records.push({name,passed:true});};try{
 for(const kind of ['auth_http','auth_malformed','auth_timeout','classifier_http','classifier_malformed','classifier_timeout'])await test(kind,async()=>{let calls=0;const fetcher=async(url)=>{calls++;if(url.includes('/auth/')){if(kind==='auth_timeout')throw Object.assign(Error('injected'),{name:'TimeoutError'});return {ok:kind!=='auth_http',json:async()=>kind==='auth_malformed'?{id:user,app_metadata:{}}:{id:user,app_metadata:{synthetic_staging_run:run}}};}if(kind==='classifier_timeout')throw Object.assign(Error('injected'),{name:'TimeoutError'});return {ok:kind!=='classifier_http',body:{cancel:async()=>{}},json:async()=>({answers:[],usage:null})};};assert.equal(await r.start(user,'How many sleep minutes yesterday?',{fetcher,env}),null);assert.equal(calls,kind.startsWith('auth')?1:2);});
 const options={userId:user,identity:{anonymous_user_id:'fixture'},timezone:'Europe/Madrid',now:Date.parse('2026-10-08T10:00:00Z'),db:async()=>[]};
 for(const [name,read]of [['read_timeout',async()=>{throw Error('injected_timeout');}],['schema_missing',async()=>({reason:'source_schema_unavailable',rows:[]})],['truncated',async()=>({available:true,rows:[],next_offset:40})],['invalid_units',async()=>({available:true,rows:[{metric:'sleep_duration',unit:'hours',value_number:7}]})],['impossible_duration',async()=>({available:true,rows:[{metric:'sleep_duration',unit:'minutes',value_number:2000}]})],['multiple_yesterday',async()=>({available:true,rows:[1,2].map(value_number=>({metric:'sleep_duration',unit:'minutes',value_number}))})]])await test(name,async()=>assert.equal(await r.prepare('sleep_yesterday',{...options,read}),null));
 await test('incomplete_statistics',async()=>assert.equal(await r.prepare('protection_week',{...options,read:async()=>({coverage:'first_10000_overlapping_rows',rows:[]})}),null));
 for(const days of [['2026-03-30T12:00:00Z',23],['2026-10-26T12:00:00Z',25]])await test('DST_'+days[1],async()=>{await r.prepare('sleep_yesterday',{...options,now:Date.parse(days[0]),read:async(u,i,q)=>{assert.equal(Date.parse(q.to)-Date.parse(q.from),days[1]*3600000);return {available:true,rows:[],next_offset:null};}});});
 const good={phase:'final',message_kind:'question',decision:'respond',action:null,memory:null,accepted_proposal:null,pending_request:null,queries:[],observations:[],followup_resolution:null,longitudinal_review:null};for(const bad of [{action:{}},{memory:{}},{queries:[{}]},{observations:[{}]},{phase:'read'}])await test('authority_'+Object.keys(bad)[0],async()=>assert.equal(await r.answer({},async()=>({...good,...bad}),{}),null));
 await test('generation_error',async()=>assert.equal(await r.answer({},async()=>{throw Error('injected');},{}),null));
 }finally{console.info=info;}fs.mkdirSync('tmp/retrieval-wide',{recursive:true});fs.writeFileSync('tmp/retrieval-wide/faults.json',JSON.stringify({provider_real:false,fault_injection:true,records,passed:records.every(x=>x.passed)},null,2));console.log('PASS '+records.length+' deterministic fault/authority/DST cases; separate from real provider run');}
main().catch(e=>{console.error(e);process.exitCode=1;});
