"use strict";
const fs=require("node:fs"),crypto=require("node:crypto"),{summarize}=require("./bm_retrieval_step_benchmark");
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");
function load(path){const bytes=fs.readFileSync(path);return {...JSON.parse(bytes),artifact_sha256:sha(bytes)};}
function audit(b,q,strictBinding=false){
 const turns=strictBinding?require("./bm_retrieval_step_quality").buildTurns(b):null;
 if(!b.complete||!q.complete||b.records.length!==b.pair_count*2||q.reviews.length!==b.records.length||q.source_run_id!==b.run_id)throw Error("incomplete_or_unbound_evidence");
 const keys=new Set();for(const r of q.reviews){const key=r.variant+":"+r.turn;if(keys.has(key))throw Error("duplicate_review");keys.add(key);if(strictBinding){const t=turns.find(t=>t.conversation_id===key);if(!t||require("./bm_sol_quality_judge").reviewDigest(t,[],r.review.model_requested)!==r.input_sha256)throw Error("quality_digest_mismatch");}if(!b.records.some(x=>x.variant===r.variant&&x.pair===r.turn))throw Error("unbound_review");}
 const summary=summarize(b.records,b.rates),a=summary.optimized,c=summary.decisions;
 const review=v=>q.reviews.filter(r=>r.variant===v),ok=r=>["excellent","acceptable"].includes(r.review?.verdict)&&!r.review.hard_contradiction&&!r.review.unsafe_claim;
 const regressions=review("decisions").filter(r=>!ok(r)&&review("optimized").some(x=>x.turn===r.turn&&ok(x))).map(r=>({pair:r.turn,case_id:b.records.find(x=>x.variant==="decisions"&&x.pair===r.turn).case_id,review:r.review}));
 const accelerated=b.records.filter(r=>r.variant==="decisions"&&r.retrieval_trace.some(t=>t.accepted));
 const delta=(a,b)=>(b/a-1)*100;
 return {summary,quality:q.by_variant,paired_quality_regressions:regressions,accelerated:{count:accelerated.length,one_generation:accelerated.filter(r=>r.model_calls===1).length,extra_generations:accelerated.filter(r=>r.model_calls>1).map(r=>({case_id:r.case_id,calls:r.model_calls}))},changes_percent:{first_text_p50:delta(a.first_text_ms.p50,c.first_text_ms.p50),first_text_p95:delta(a.first_text_ms.p95,c.first_text_ms.p95),final_p50:delta(a.final_ms.p50,c.final_ms.p50),final_p95:delta(a.final_ms.p95,c.final_ms.p95),complete_estimated_cost:a.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd!=null?delta(a.total_estimated_cost_usd,c.total_estimated_cost_usd):null},
 gates:{no_visible_catalog_references:b.records.filter(r=>r.variant==="decisions").every(r=>require("../netlify/functions/bmb-sources").cleanCitations(r.synthetic_response||"",{quotedIn:r.synthetic_input})===(r.synthetic_response||"").trim()),visible_prose_clean:b.records.filter(r=>r.variant==="decisions").every(r=>!/[\uE200-\uE202]/u.test(r.synthetic_response||"")&&!/\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b/i.test(r.synthetic_response||"")),all_candidate_outputs_acceptable_by_model:review("decisions").every(ok),at_least_95_percent_excellent_by_model:review("decisions").filter(r=>r.review?.verdict==="excellent"&&ok(r)).length/review("decisions").length>=.95,no_new_paired_quality_failures:regressions.length===0,no_more_functional_errors:c.errors<=a.errors,zero_candidate_functional_errors:c.errors===0,first_text_faster:c.first_text_ms.p50<a.first_text_ms.p50,final_faster:c.final_ms.p50<a.final_ms.p50,first_text_p95_faster:c.first_text_ms.p95<a.first_text_ms.p95,final_p95_faster:c.final_ms.p95<a.final_ms.p95,lower_complete_estimated_cost:a.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd!=null&&c.total_estimated_cost_usd<a.total_estimated_cost_usd,cleanup_all_passed:b.cleanup.length===5&&b.cleanup.every(r=>r.passed)}};
}
function main(){
 const file="docs/BM_RETRIEVAL_ITERATION_EVIDENCE_2026-10-08.json",previous=load(file),base="tmp/retrieval-iteration/",benchmark=load(base+"regression.json"),quality=load(base+"regression-quality.json"),verification=load(base+"regression-source-verification.json");
 if(verification.run_id!==benchmark.run_id||verification.files.length!==14||!verification.files.every(r=>r.passed&&r.expected===r.actual))throw Error("invalid_frozen_source_verification");
 const tracked=[];
 const cp=require("node:child_process");
 for(const row of verification.files){const root=row.variant==="optimized"?"../Codigo-retrieval-reference":".",current=fs.readFileSync(root+"/netlify/functions/"+row.name,"utf8").replace(/\r\n/g,"\n");
  let expected=cp.execFileSync("git",["-C",root,"show",benchmark.source_commits[row.variant]+":netlify/functions/"+row.name],{encoding:"utf8"}).replace(/\r\n/g,"\n");
  if(row.name==="bmb-sources.js")expected=expected.replace('function cleanCitations(text){if(typeof text!=="string")return text;', 'function cleanCitations(text,{quotedIn=""}={}){if(typeof text!=="string")return text;\n const refs=SOURCE_NAMES.filter(id=>!quotedIn.includes("["+id+"]")&&!new RegExp("\\\\b(?:Fuente|Source)\\\\s*:?\\\\s*"+id+"(?:\\\\.|(?=\\\\s|$))","i").test(quotedIn));').replace('SOURCE_NAMES.includes(id.trim())','refs.includes(id.trim())').replace('const names=SOURCE_NAMES.join("|");','if(!refs.length)return value.trim();\n const names=refs.join("|");').replaceAll('SOURCE_NAMES.some(id=>id.startsWith','refs.some(id=>id.startsWith').replace('id.startsWith(label[1])','id.startsWith(label[1].toLowerCase())');
  if(row.name==="bmb-brain.js")expected=expected.replace('cleanCitations(input.retrieval_contract?require("./bm-retrieval-step").cleanProse(text):text)', 'cleanCitations(input.retrieval_contract?require("./bm-retrieval-step").cleanProse(text):text,{quotedIn:input.current_message})').replace('onDraft(cleanCitations(text))','onDraft(cleanCitations(text,{quotedIn:input.current_message}))').replace('cleanCitations(result.response_text);','cleanCitations(result.response_text,{quotedIn:prompt});').replace('cleanCitations(result.response_text||"");','cleanCitations(result.response_text||"",{quotedIn:prompt});');
  if(current!==expected)throw Error("unmeasured_change_beyond_citation_compatibility");tracked.push({variant:row.variant,name:row.name,current_sha256:sha(fs.readFileSync(root+"/netlify/functions/"+row.name)),only_declared_compatibility_changes:true});
 }
 const analysis=audit(benchmark,quality,true),missing=[];
 for(const r of benchmark.records.filter(r=>r.variant==="decisions"))for(const p of r.provider_requests.filter(p=>!p.usage)){
  const prior=previous.final.benchmark.records.flatMap(x=>x.provider_requests).find(x=>x.endpoint===p.endpoint&&x.request_sha256===p.request_sha256&&x.usage);
  missing.push({case_id:r.case_id,endpoint:p.endpoint,request_sha256:p.request_sha256,actual_usage_unknown:true,...(prior?{identical_prior_payload_input_tokens:prior.usage.input_tokens,inferred_standard_cost_usd:require("./bm_decisions_meter").estimate(prior,benchmark.rates),provenance:"Estimate from an identical previously metered request payload, not observed usage for this aborted request"}:{})});
 }
 const inference=missing.every(r=>r.inferred_standard_cost_usd!=null)?analysis.summary.decisions.known_estimated_cost_usd+missing.reduce((s,r)=>s+r.inferred_standard_cost_usd,0):null;
 const cleaner=require("../netlify/functions/bmb-sources").cleanCitations,compatibility={post_measurement_change:"Preserve source strings explicitly quoted in current user text; uppercase partial-label handling",real_provider_repeated_after_this_guard:false,all_recorded_visible_outputs_unchanged:benchmark.records.every(r=>cleaner(r.synthetic_response||"",{quotedIn:r.synthetic_input})===(r.synthetic_response||"").trim()),targeted_runtime_tests_passed:true};
 if(!compatibility.all_recorded_visible_outputs_unchanged)throw Error("compatibility_changed_measured_outputs");
 // Main 40-pair validation was independently frozen before the shared renderer fix.
 previous.final.analysis=audit(previous.final.benchmark,previous.final.quality,true);
 const evidence={...previous,generated_at:new Date().toISOString(),synthetic_gate_passed:Object.values(analysis.gates).every(Boolean),activation:false,last_validation:{benchmark,quality,analysis,frozen_source_verification:verification,post_measurement_compatibility:compatibility,current_source_validation:tracked,missing_request_estimates:missing,inferred_total_standard_cost_usd:inference,inferred_cost_change_percent:inference==null?null:(inference/analysis.summary.optimized.total_estimated_cost_usd-1)*100},
  current_sources:{candidate:require("node:child_process").execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim(),baseline:require("node:child_process").execFileSync("git",["-C","../Codigo-retrieval-reference","rev-parse","HEAD"],{encoding:"utf8"}).trim()},
  last_validation_limitations:["20 previously executed regression questions; not an unseen validation corpus","The earlier 40-pair comparison has complete usage and 56.7% lower estimated API cost; this final 20-pair repeat has one missing classifier usage record","A same-payload estimate is explicitly inferred, never substituted for missing measured usage; complete-cost gate remains false","Citation compatibility guard followed the measured runtime; all recorded visible outputs remain identical and targeted runtime tests pass","Global chat traffic, native transport, physical iPhone, human review and actual billing invoice remain untested"]};
 delete evidence.artifact_sha256;
 fs.writeFileSync(file,JSON.stringify(evidence,null,2)+"\n");console.log(JSON.stringify({...analysis,missing_request_estimates:missing,inferred_total_standard_cost_usd:inference,compatibility,synthetic_gate_passed:evidence.synthetic_gate_passed}));
}
if(require.main===module)try{main();}catch(e){console.error(e.message);process.exitCode=1;}
module.exports={audit};
