"use strict";
const fs=require('fs'),crypto=require('crypto'),judge=require('./bm_sol_quality_judge'),meter=require('./bm_decisions_meter');
const arg=(k,d)=>process.argv.includes(k)?process.argv[process.argv.indexOf(k)+1]:d;
const sha=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
function buildTurns(report){return report.records.map(r=>({conversation_id:r.variant+':'+r.pair,turn:r.step,input:r.synthetic_input,response:r.synthetic_response||'',status:r.passed?'passed':'failed',channel:'app',history:r.expected.history||[],expected:{...r.expected,current_time:report.fixture_clock,timezone:'Europe/Madrid',language:r.step>0&&/en inglés|in English/i.test(r.synthetic_input)?'en':r.step>0&&/en español|in Spanish/i.test(r.synthetic_input)?'es':r.language,eligible:r.eligible,required_action:['action','actions_combined'].includes(r.group)?'Prepare immediate selected_distractions start_protection 30 minutes, no device success claim.':r.group==='forget'?'Forget personal data durably; no device action.':'No device action. Questions/quotes/hypotheticals must not save new personal facts.',quality_criterion:'Evaluate exact facts against raw supplied fixtures and preceding conversation, not just expected minutes. Invalid-unit records must not be silently interpreted as minutes. Missing sleep is unknown; measured zero is known zero. Weekly sleep averages available observations only, not missing nights. Protection is union of clipped intervals, not saved time or usage. Distinguish declaration, synthetic fixture and native measurement. No internal citation syntax/UUIDs/source labels in visible prose except user-requested quotation. Output may correctly convert/round minutes to whole hours/minutes. Respect the current question rather than forcing duration onto a wording/provenance/advice task.'},evaluation_context:{has_selected_apps:true,screen_time_authorized:true,device_execution_ready:true},actual:{visible:r.synthetic_response||'',actions:r.pending_action?[r.pending_action]:[],auto_apply:r.auto_apply,physical_execution:false,personal_record_integrity:r.personal_record_integrity||null}}));}
async function main(){if(!process.argv.includes('--run'))throw Error('explicit_review_required');const report=JSON.parse(fs.readFileSync(arg('--input','tmp/retrieval-wide/final.json')));if(!report.complete)throw Error('complete_required');
 // All eligible cases plus a frozen 12-scenario/24-case negative stratum, all functional failures.
 const negativeIndices=new Set([0,4,6,9,12,14,17,18,20,22,25,39]);const ids=new Set(report.case_manifest.cases.filter(s=>s.eligible||negativeIndices.has(Math.floor((Number(s.id.split('-')[1])-81)/2))).map(s=>s.id));
 const turns=buildTurns(report).filter((t,i)=>(process.argv.includes("--all-turns")||ids.has(report.records[i].case_id)||!report.records[i].passed)&&(!arg("--variant",null)||t.conversation_id.startsWith(arg("--variant",null)+":"))),file=arg('--output','tmp/retrieval-wide/quality.json');
 const prior=fs.existsSync(file)?JSON.parse(fs.readFileSync(file)):null;const previous=prior?.reviews||[];const failures=prior?.attempt_failures||[];if(prior?.error&&!failures.length){const failed=turns[previous.length];failures.push({conversation_id:failed.conversation_id,turn:failed.turn,input_sha256:judge.reviewDigest(failed,failed.history||[]),error:prior.error,no_retry:true});}const remaining=turns.filter(t=>!failures.some(f=>f.conversation_id===t.conversation_id&&f.turn===t.turn));const budgetFile=arg('--budget-file','tmp/retrieval-wide/budget.json'),requestsFile=arg('--requests-file','tmp/retrieval-wide/reviewer-requests.json'),requests=fs.existsSync(requestsFile)?JSON.parse(fs.readFileSync(requestsFile)):[];
 const rates={input:4,cached:.4,output:20,source:'https://developers.openai.com/api/docs/models/gpt-5.6-sol',verified:'2026-10-09'};
 const fetchImpl=async(url,options)=>{if(url!=='https://api.openai.com/v1/responses')throw Error('review_target');const p=JSON.parse(options.body),upper=(Buffer.byteLength(options.body,'utf8')*rates.input*1.25+p.max_output_tokens*rates.output)/1e6;
 const budget=JSON.parse(fs.readFileSync(budgetFile));if(budget.reserved_upper_usd+upper>budget.limit_usd)throw Error('review_spend_limit');budget.reserved_upper_usd+=upper;budget.requests++;fs.writeFileSync(budgetFile,JSON.stringify(budget,null,2));const row={endpoint:'responses',request_sha256:sha(p),reserved_upper_usd:upper};requests.push(row);fs.writeFileSync(requestsFile,JSON.stringify(requests,null,2));
 try{let r=await fetch(url,options);r=await meter.meterResponse(r,row);const measured=meter.estimate(row,rates),latest=JSON.parse(fs.readFileSync(budgetFile));if(measured!==null){latest.known_usd+=measured;latest.reserved_upper_usd-=upper-measured;latest.reviewer_known_usd=(latest.reviewer_known_usd||0)+measured;}fs.writeFileSync(budgetFile,JSON.stringify(latest,null,2));return r;}catch(e){row.error=e.name;throw e;}finally{fs.writeFileSync(requestsFile,JSON.stringify(requests,null,2));}};
 await judge.reviewTurns(remaining,{concurrency:1,previousReviews:previous,judgeOptions:{maxAttempts:1,fetchImpl},onCheckpoint:(reviews,error)=>{const isolated=reviews.map(r=>({...r,variant:r.conversation_id.split(':')[0]}));fs.writeFileSync(file,JSON.stringify({source_run_id:report.run_id,criteria_version:'wide-facts-context-v1',model_review_not_human:true,selected_turn_count:turns.length,all_turn_count:report.records.length,complete:reviews.length===turns.length&&!error,attempted_all:reviews.length+failures.length===turns.length&&!error,attempt_failures:failures,error:error||failures[0]?.error||null,reviewer_rates:rates,reviews:isolated,by_variant:Object.fromEntries(['optimized','decisions'].map(v=>[v,judge.summarize(isolated.filter(r=>r.variant===v))]))},null,2));}});console.log(JSON.stringify(JSON.parse(fs.readFileSync(file)).by_variant));
}
module.exports={buildTurns};if(require.main===module)main().catch(e=>{console.error(['review_spend_limit','complete_required'].includes(e.message)?e.message:'wide_quality_failed');process.exitCode=1;});
