"use strict";
const assert=require("node:assert/strict");
const policy=require("../netlify/functions/bmb-policy");
const membership=require("../netlify/functions/_membership");
let history=[],calls=[],saved=[];
membership.supabaseFetch=async(path,options)=>{
  calls.push({path,options});
  if(path.startsWith("bm_brain_memories"))return saved;
  if(path.startsWith("bmb_accounts"))return [];
  if(path.startsWith("assistant_app_turns"))return history;
  if(path.startsWith("bmb_sessions"))return [];
  throw Error(path);
};
const brain=require("../netlify/functions/bmb-brain");
const base=()=>({phase:"final",response_text:"I can help you protect your evening.",response_language:"en",message_kind:"statement",decision:"respond",evidence:"help",accepted_proposal:null,pending_request:null,action:null,queries:[],memory:null,cited_sources:[]});
const action=(extra={})=>({type:"start_protection",minutes:30,start_minute:null,end_minute:null,weekdays:[],duration_days:null,local_date:null,timezone:null,recurrence:"once",window_id:null,hours:null,hard_mode:false,...extra});
const context=()=>({language:"en",memory:{semantic_store_version:0},has_selected_apps:true,screen_time_authorized:true,brain_snapshot:{schema_version:1,generated_at:new Date().toISOString(),timezone:"Europe/Madrid",sessions:[],local_date:"2026-10-03"}});
async function turn(response,ctx=context(),prompt="help") {return brain.plan({prompt,context:ctx,userId:"A",identity:{anonymous_user_id:"verified-A"}},{run:async()=>response});}
async function main() {
  let response=base(), result=await turn(response);
  assert.equal(result.plan.bmb_generated,true);assert.deepEqual(result.plan.actions,[]);
  response={...base(),message_kind:"question",decision:"propose",action:action()};result=await turn(response);
  assert.equal(result.plan.actions.length,0);assert.equal(result.context.brain_request.execute,false);
  const proposed=result.plan.bmb_state.proposal;
  const ctx=context();ctx.memory.conversation_state={bmb_state:{proposal:proposed}};
  result=await turn({...base(),message_kind:"statement",decision:"respond"},ctx);
  assert.equal(result.plan.bmb_state.proposal.fingerprint,proposed.fingerprint,"Detour erased proposal");
  await assert.rejects(()=>turn({...base(),message_kind:"statement",decision:"execute",action:action()},ctx),/not_authorized/);
  await assert.rejects(()=>turn({...base(),message_kind:"acceptance",decision:"execute",accepted_proposal:proposed.fingerprint,action:action({minutes:45})},ctx),/not_authorized/);
  result=await turn({...base(),message_kind:"acceptance",decision:"execute",accepted_proposal:proposed.fingerprint,action:action()},ctx);
  assert.equal(result.plan.actions[0].minutes,30);assert.equal(result.context.brain_request.execute,true);
  const expired=context();expired.memory.conversation_state={bmb_state:{proposal:{...proposed,expires_at:"2020-01-01"}}};
  await assert.rejects(()=>turn({...base(),message_kind:"acceptance",decision:"execute",accepted_proposal:proposed.fingerprint,action:action()},expired),/not_authorized/);
  result=await turn({...base(),message_kind:"action_request",decision:"execute",action:action()});assert.equal(result.plan.actions.length,1);
  const stale=context();stale.brain_snapshot.generated_at="2020-01-01";
  await assert.rejects(()=>turn({...base(),message_kind:"action_request",decision:"execute",action:action()},stale),/stale_device/);
  result=await turn({...base(),message_kind:"cancellation",decision:"cancel"},ctx);assert.equal(result.plan.bmb_state.proposal,null);assert.equal(result.plan.bmb_invalidates,true);
  await assert.rejects(()=>turn({...base(),response_text:"Your evening: protected"}),/invalid_prose/);
  assert.equal((await turn({...base(),response_text:"Let's start at 22:30."})).plan.response_text,"Let's start at 22:30.");
  await assert.rejects(()=>turn({...base(),cited_sources:["other-user"]}),/unknown_citation/);
  await assert.rejects(()=>turn({...base(),memory:{operation:"set",key:"goal",value:"help",evidence:"help"},message_kind:"question"}),/ungrounded_memory/);
  result=await turn({...base(),memory:{operation:"set",key:"goal",value:"help",evidence:"help"}});assert.equal(result.context.brain_memory_effect.value,"help");
  saved=[{key:"goal",value:null,source_at:"2026-10-01T00:00:00Z"}];calls=[];
  await turn(base());assert(calls.some(c=>c.path.includes("created_at=gt.2026-10-01")),"Forgotten history resurfaced");saved=[];
  history=Array.from({length:41},(_,i)=>({id:String(i),user_text:"old fact",created_at:"2020-01-01"}));
  const page=await brain.readSource("A",{anonymous_user_id:"verified-A"},{source:"history",term:"old",offset:0},null);
  assert.equal(page.next_offset,40);assert.equal(page.rows.length,40);
  assert(calls.at(-1).path.includes("auth_user_id=eq.A"));assert(!calls.at(-1).path.includes("eq.B"));
  assert.equal((await brain.readSource("A",null,{source:"features",offset:0},null)).reason,"no_verified_account_link");history=[];
  const once=action({type:"apply_schedule",minutes:null,start_minute:1350,end_minute:420,local_date:"2027-01-05",timezone:"Europe/Madrid"});
  const dated=brain.normalizeAction(once,Date.parse("2027-01-05T12:00:00Z"));
  assert.equal(dated.starts_at,"2027-01-05T21:30:00.000Z");assert.equal(dated.ends_at,"2027-01-06T06:00:00.000Z");assert.deepEqual(dated.weekdays,[]);
  assert.throws(()=>brain.normalizeAction({...once,local_date:"2027-03-28",start_minute:150,end_minute:240},Date.parse("2027-03-27")),/missing_local_time/);
  assert.throws(()=>brain.normalizeAction({...once,local_date:"2026-10-25",start_minute:150,end_minute:240},Date.parse("2026-10-24")),/ambiguous/);
  assert.throws(()=>brain.normalizeAction({...once,local_date:"2020-01-01"}),/invalid_once/);
  assert.equal(brain.normalizeAction({...once,recurrence:"continuous",local_date:null,weekdays:[1,2],duration_days:null}).duration_days,null);
  const p=policy.settings({timezone:"Europe/Madrid",grant:{active:true,action_types:["start_protection"],expires_at:"2027-01-01",start_minute:1320,end_minute:480},notifications:{enabled:true}});
  assert.equal(policy.actionGate(action(),p,context(),Date.parse("2026-10-03T21:00:00Z")).allowed,true);
  assert.equal(policy.actionGate(action(),p,context(),Date.parse("2026-10-03T12:00:00Z")).allowed,false);
  assert.equal(policy.actionGate(action({minutes:45}),p,context(),Date.parse("2026-10-03T21:00:00Z")).allowed,false);
  assert.equal(policy.actionGate(action(),{...p,grant:{...p.grant,active:false}},context()).allowed,false);
  assert.equal(policy.actionGate(action(),p,{...context(),vacation_mode_active:true},Date.parse("2026-10-03T21:00:00Z")).allowed,false);
  const event={kind:"opportunity",expires_at:"2027-01-01"},nc={notification_authorized:true};
  assert.equal(policy.notificationGate(event,p,nc,Date.parse("2026-10-03T12:00:00Z")).allowed,true);
  assert.equal(policy.notificationGate(event,p,{...nc,chat_active_until:"2027-01-01"},Date.parse("2026-10-03T12:00:00Z")).allowed,false);
  assert.equal(policy.notificationGate(event,p,nc,Date.parse("2026-10-03T21:00:00Z")).allowed,false);
  assert.equal(policy.notificationGate({...event,expires_at:"2020-01-01"},p,nc).allowed,false);
  assert.equal(policy.settings().notifications.max_per_day,1);assert.equal(policy.settings().notifications.max_per_week,3);
  const push=require("../netlify/functions/_assistant_push").pushPayload({id:"x"},{silent:true});assert.equal(push.aps.alert,undefined);assert.equal(push.bm_autonomous,true);
  const prose=require("../netlify/functions/assistant-app").visibleReply({bmb_generated:true,message_text:"I'll give this a try.",actions:[action()]},context(),action());assert.equal(prose,"I'll give this a try.");
  console.log("BMB: generative output, exact acceptance, detours/cancellation, account history/pagination, memory tombstones, date/DST/overnight/continuous schedules, current grants/pauses/revocation and separate notifications passed");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
