"use strict";
// Independent factual gold, authored before replay. IDs alone add no coverage.
const fs=require('node:fs'),{validateDataset}=require('./bm_semantic_replay'),{digest}=require('./bm_semantic_oracle');
const {dayOffset,midnight,periodBounds}=require('../netlify/functions/bm-brain-data');
function authoredSources(fixture){
 const {profile,clock,route}=fixture,timezone='Europe/Madrid',today=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(clock));
 const dates=[-3,-2,-1].map(n=>dayOffset(today,n)),iso=date=>new Date(midnight(date,timezone)+3600000).toISOString();
 const sleep_rows=profile==='missing'?[]:dates.map((date,i)=>({date,value_number:[421,482,543][i],unit:profile==='invalid'?'hours':'minutes',source:profile==='declared'?'user_report':'native_health',measurement:profile==='declared'?'declared':'measured'}));
 const duration=profile==='sparse'?30:75,start=iso(dates[2]),end=new Date(Date.parse(start)+duration*60000).toISOString();
 const protection_sessions=profile==='missing'?[]:[{started_at:start,ended_at:end,...(profile==='zero'?{pause_started_at:start,pause_ended_at:end}:{})},...(profile==='overlap'?[{started_at:new Date(Date.parse(start)+30*60000).toISOString(),ended_at:new Date(Date.parse(start)+90*60000).toISOString()}]:[])];
 const native_nights=profile==='native'?dates.map((date,i)=>({date,source:'apple_health',sleep_minutes:[421,482,543][i]})):[];
 const bounds=periodBounds({period:route.endsWith('week')?'this_week':'yesterday'},{timezone,week_starts_on:2},Date.parse(clock));
 return {route,profile,clock,timezone,sleep_rows,current_sleep:{available:native_nights.length>0,nights:native_nights},protection_sessions,queried_period:{from:new Date(bounds.from).toISOString(),to:new Date(bounds.to).toISOString()},allowed_observation_clocks:[1380,60],interpretation:'These are the actual supplied source records, not default recipe values. Account observations and the current iPhone summary are distinct sources. Empty current_sleep never means account sleep rows are absent.'};
}
function build({clock=new Date().toISOString(),version=2}={}){
 const conversations=[];
 const texts={
 sleep_yesterday:{es:['¿Cuánto sueño registré ayer?','Dime cuánto dormí ayer según mis registros.','Consulta la duración de mi sueño registrado ayer.','¿Qué duración consta para mi sueño de ayer?','Muéstrame en minutos el sueño que registré ayer.'],en:['How much sleep did I record yesterday?','Tell me how long I slept yesterday according to my records.','Retrieve my recorded sleep duration yesterday.','What duration is on record for my sleep yesterday?','Show my sleep recorded yesterday in minutes.']},
 sleep_week:{es:['¿Cuál es mi media de sueño registrada esta semana?','Dime la duración media de mis registros de sueño esta semana.','Consulta mi promedio de sueño de esta semana natural.','¿Qué media de duración tienen mis registros de sueño esta semana?','Muéstrame en minutos mi media de sueño registrada esta semana.'],en:['What is my recorded sleep average this week?','Tell me the average duration of my sleep records this week.','Retrieve my mean sleep for this calendar week.','What mean duration do my sleep records have this week?','Show my recorded sleep average this week in minutes.']},
 protection_yesterday:{es:['¿Cuánta protección tengo registrada ayer?','Dime la duración total de mi protección registrada ayer.','Consulta mis minutos de protección de ayer.','¿Qué total de protección consta en mis registros de ayer?','Muéstrame mi protección registrada ayer en minutos.'],en:['How much protection do I have recorded yesterday?','Tell me my total recorded protection duration yesterday.','Retrieve my protection minutes from yesterday.','What protection total is on record for me yesterday?','Show my recorded protection yesterday in minutes.']},
 protection_week:{es:['¿Cuánta protección acumulé según mis registros esta semana?','Dime la duración total de mi protección registrada esta semana.','Consulta mis minutos de protección de esta semana natural.','¿Qué total tienen mis registros de protección esta semana?','Muéstrame mi protección registrada esta semana en minutos.'],en:['How much protection did I accumulate according to my records this week?','Tell me my total recorded protection duration this week.','Retrieve my protection minutes for this calendar week.','What total do my protection records have this week?','Show my recorded protection this week in minutes.']}};
 const state={intent:'general',apps:null,app_category:null,moment:null,action_type:null,hard_mode:null,requested_capability:null,start:null,end:null,duration_minutes:null,recurrence:null,schedule_horizon_days:null,confirmation:null,pending_slots:[],status:'idle',next_question:null};
 for(const [route,languages]of Object.entries(texts))for(const [language,questions]of Object.entries(languages))for(const profile of route.startsWith('sleep')?['measured','declared','missing','invalid','native']:['recorded','zero','missing','overlap','sparse'])for(const [index,input]of questions.entries()){
  const fixture={route,profile,clock,sleep_minutes:[421,482,543],protection_minutes:75,allowed_observation_clocks:[1380,60]};
  const supplied=authoredSources(fixture),bounds=supplied.queried_period,within=date=>{const t=midnight(date,'Europe/Madrid');return t>=Date.parse(bounds.from)&&t<Date.parse(bounds.to);},nights=supplied.sleep_rows.filter(r=>within(r.date)),valid=nights.filter(r=>r.unit==='minutes');
  const hasPeriodSession=supplied.protection_sessions.some(r=>Date.parse(r.started_at)<Date.parse(bounds.to)&&Date.parse(r.ended_at)>Date.parse(bounds.from));
  const facts=route.startsWith('sleep')?{metric:'sleep_duration',period:route.endsWith('week')?'this_calendar_week':'yesterday',expected_minutes:valid.length?valid.reduce((n,r)=>n+r.value_number,0)/valid.length:null,measurement:profile==='declared'?'declared':profile==='missing'?'absent':profile==='invalid'?'unsupported_hours_unit':'measured',night_count:nights.length,valid_night_count:valid.length,rule:'Absent/invalid values are unknown, never zero. Only declared entries are self-reported. Native and measured fixtures describe measured records. The last dated entry is yesterday.'}:{metric:'recorded_protection_duration',period:route.endsWith('week')?'this_calendar_week':'yesterday',expected_minutes:!hasPeriodSession||profile==='zero'?0:profile==='overlap'?90:profile==='sparse'?30:75,rule:'Total recorded protection only. Empty persisted-session records yield a known recorded zero; a completely paused session also has zero protected duration. Never infer actual phone usage, time saved or physical execution. Overlapping intervals are unioned, not added.'};
  if(version===3){
   supplied.sleep_rows=supplied.sleep_rows.map(r=>({...r,measured_at:new Date(midnight(r.date,supplied.timezone)+3600000).toISOString(),timezone:supplied.timezone,local_date:r.date,local_date_timezone:supplied.timezone}));
   if(route.startsWith('protection'))supplied.returned_protection_statistics={available:true,protected_seconds:facts.expected_minutes*60,session_count:hasPeriodSession?(profile==='overlap'?2:1):0,break_count:0,partial:true,metric:'recorded_protection_duration',saved_time_available:false,coverage:'all_persisted_overlapping_rows',partial_meaning:'This is the actual source partial flag. It qualifies coverage/freshness of the records, not measured physical protection. Saying the records are marked partial is supported; claiming physical execution, usage or time saved is not.'};
  }
  conversations.push({id:`bmb-${route}-${profile}-${language}-${index+1}`,channel:'ios',context:{language,has_selected_apps:true,selection_count:2,screen_time_authorized:true,device_execution_ready:true,bmb_release_fixture:fixture},turns:[{input,expect:{state:{...state},decision:{type:'none',slot:null},actions:[],language,factual_expectation:{...facts,requested_minutes:/minut/iu.test(input),source_fixture:supplied,quality_criterion:'Check this exact factual question, period, units and source provenance against the supplied independently authored fixture. No actions, memory or observation writes. Hours/minutes must preserve the exact available value. Missing nights are unknown. Native sleep is not a user declaration. Records are synthetic test fixtures, not a real device measurement.'}}}]});
 }
 const dataset={version:1,id:'bmb-decisions-factual-200-v'+version+'-2026-10-09',split:'development',provenance:'200 unique normalized input plus factual expectation sequences: four factual routes, ES/EN, five source conditions and five independently authored phrasings. V2 names materialized source rows rather than unmaterialized recipe defaults. Zero protection has a completely paused session; sparse protection has30minutes; these are different actual fixtures from missing/recorded75. Live provider with isolated in-memory account fixtures; real authenticated database/NDJSON behavior is measured separately by the matched broad benchmark. No physical device or human review is implied.'+(version===3?' V3 also supplies original UTC timestamps/local dates and the actual returned protection_statistics partial flag, tested against the server read. Previous datasets and verdicts remain unchanged.':''),conversations};validateDataset(dataset);
 if(new Set(conversations.map(c=>digest(c.turns.map(t=>({input:t.input.normalize('NFC').replace(/\s+/gu,' ').trim().toLowerCase(),expected:t.expect}))))).size!==200)throw Error('unique_coverage');return dataset;
}
if(require.main===module){const version=process.argv.includes('--v3')?3:2,file='tools/datasets/bmb_decisions_release_200_v'+version+'_2026-10-09.json';fs.writeFileSync(file,JSON.stringify(build({version}),null,2));console.log(file);}
module.exports={build,authoredSources};
