-- Content-free usage reservations. A consumed request is never regenerated by
-- transport retries. Replay uses a new request ID and consumes the same budget.
create table if not exists public.assistant_voice_requests (
  request_id uuid primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  turn_id uuid not null references public.assistant_app_turns(id) on delete cascade,
  created_at timestamptz not null default clock_timestamp()
);
create index if not exists assistant_voice_requests_user_time_idx
  on public.assistant_voice_requests(auth_user_id, created_at desc);
create index if not exists assistant_voice_requests_time_idx
  on public.assistant_voice_requests(created_at desc);
alter table public.assistant_voice_requests enable row level security;
revoke all on public.assistant_voice_requests from public, anon, authenticated;
grant select on public.assistant_voice_requests to service_role;

create or replace function public.reserve_assistant_voice(
  p_auth_user_id uuid, p_turn_id uuid, p_request_id uuid
) returns table(reserved boolean, reason text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_now timestamptz := clock_timestamp();
begin
  -- Serialize the global budget and deduplication across function instances.
  perform pg_advisory_xact_lock(1791384106);
  if exists (select 1 from assistant_voice_requests where request_id = p_request_id) then
    return query select false, 'duplicate'::text; return;
  end if;
  if not exists (select 1 from assistant_app_turns where id = p_turn_id
    and auth_user_id = p_auth_user_id and status = 'completed') then
    return query select false, 'unavailable'::text; return;
  end if;
  if (select count(*) from assistant_voice_requests where auth_user_id = p_auth_user_id
    and created_at > v_now - interval '1 hour') >= 20
    or (select count(*) from assistant_voice_requests where auth_user_id = p_auth_user_id
    and created_at > v_now - interval '24 hours') >= 100
    or (select count(*) from assistant_voice_requests
    where created_at > v_now - interval '24 hours') >= 1000 then
    return query select false, 'rate_limited'::text; return;
  end if;
  insert into assistant_voice_requests(request_id, auth_user_id, turn_id)
    values(p_request_id, p_auth_user_id, p_turn_id);
  return query select true, 'reserved'::text;
end;
$$;
revoke all on function public.reserve_assistant_voice(uuid, uuid, uuid) from public, anon, authenticated;
grant execute on function public.reserve_assistant_voice(uuid, uuid, uuid) to service_role;
